

---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(p8105.datasets)
library(plotly)
library(tidyverse)
library(viridis)
library(survminer)
library(survival)
library(flexdashboard)
library(dplyr)
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
load('./data/df_combine.RData')
df_combine <- df_combine %>% 
  head(10)

risk_vectors <- c("drug","gender")
district_vectors <- c("A","B","C")

df_combine$survival = with(df_combine, Surv(days, tb == "Yes"))

km <- survfit(survival ~ 1, data = df_combine, conf.type = "log-log")
km_by_gender <- survfit(survival ~ gender, data = df_combine, conf.type = "log-log")

selectInput("risk_vector", label = h3("Select Risk Vectors"),
                 choices = risk_vectors, selected = "gender")

selectInput("district_vector", label = h3("Select District"),
                 choices = district_vectors, selected = "A")

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlot(
      if(input$risk_vector=="gender"){
        km =  survfit(survival ~ gender, data = df_combine, conf.type = "log-log")
        ggsurvplot(km, 
                   data = df_combine, 
                   risk.table = F, 
                   pval = T, 
                   ylab = paste0("o","1"), 
                   ylim = c(0.9, 1.0))
      }else{
        km =  survfit(survival ~ drug, data = df_combine, conf.type = "log-log")
        ggsurvplot(km, 
                   data = df_combine, 
                   risk.table = F, 
                   pval = T, 
                   ylab = paste0("o","1"), 
                   ylim = c(0.9, 1.0))
      }
  )
```

